# Generated by Django 5.2.6 on 2025-09-14 23:27

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Study plan title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Study plan description and goals')),
                ('start_date', models.DateField(help_text='Study plan start date')),
                ('end_date', models.DateField(help_text='Study plan end date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the study plan', max_length=20)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Progress percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('plan_data', models.JSONField(default=dict, help_text='Structured study plan data (topics, schedule, milestones)')),
                ('plan_embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Vector embedding for semantic search (pgvector-ready)', null=True, size=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this study plan is for', on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='courses.course')),
                ('user', models.ForeignKey(help_text='User who owns this study plan', on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Plan',
                'verbose_name_plural': 'Study Plans',
                'db_table': 'study_plans_studyplan',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course', 'title')},
            },
        ),
    ]
