# Generated by Django 5.2.6 on 2025-09-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyplan',
            name='plan_embedding',
        ),
    ]
