# Generated by Django 5.2.6 on 2025-09-14 23:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Course name', max_length=200)),
                ('code', models.CharField(blank=True, help_text='Course code (e.g., CS101, MATH201)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Course description')),
                ('instructor', models.CharField(blank=True, help_text='Instructor name', max_length=100)),
                ('credits', models.IntegerField(default=3, help_text='Number of credit hours', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('semester', models.CharField(blank=True, help_text='Semester (e.g., Fall 2024, Spring 2025)', max_length=50)),
                ('start_date', models.DateField(blank=True, help_text='Course start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Course end date', null=True)),
                ('class_schedule', models.JSONField(blank=True, default=dict, help_text='Class schedule information (days, times, location)')),
                ('syllabus_text', models.TextField(blank=True, help_text='Syllabus or course content text')),
                ('difficulty_level', models.IntegerField(default=3, help_text='Difficulty level from 1 (easy) to 5 (very hard)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the course is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this course', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses_course',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Assignment title', max_length=200)),
                ('assignment_type', models.CharField(choices=[('homework', 'Homework'), ('quiz', 'Quiz'), ('exam', 'Exam'), ('project', 'Project'), ('lab', 'Lab'), ('essay', 'Essay'), ('presentation', 'Presentation'), ('discussion', 'Discussion'), ('other', 'Other')], default='homework', help_text='Type of assignment', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Assignment description or instructions')),
                ('due_date', models.DateTimeField(help_text='Assignment due date and time')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Estimated hours to complete', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Assignment weight in final grade (percentage)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.DecimalField(blank=True, decimal_places=2, help_text='Grade received (percentage)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='not_started', help_text='Current status of the assignment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this assignment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'courses_assignment',
                'ordering': ['due_date'],
            },
        ),
    ]
