# Generated by Django 5.2.6 on 2025-09-21 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Assignment file title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Assignment description or instructions')),
                ('file', models.FileField(help_text='Assignment file (PDF, DOCX, TXT, etc.)', upload_to='courses/assignments/')),
                ('file_type', models.CharField(blank=True, help_text='Detected file type', max_length=20)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this assignment has been processed by the RAG pipeline')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if RAG processing failed')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this assignment file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_files', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Assignment File',
                'verbose_name_plural': 'Course Assignment Files',
                'db_table': 'courses_assignment_file',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Quiz title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Quiz description or notes')),
                ('file', models.FileField(help_text='Quiz file (PDF, DOCX, TXT, etc.)', upload_to='courses/quizzes/')),
                ('file_type', models.CharField(blank=True, help_text='Detected file type', max_length=20)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this quiz has been processed by the RAG pipeline')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if RAG processing failed')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this quiz belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_files', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Quiz',
                'verbose_name_plural': 'Course Quizzes',
                'db_table': 'courses_quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_text', models.TextField(blank=True, help_text='Syllabus text content pasted by user')),
                ('syllabus_file', models.FileField(blank=True, help_text='Uploaded syllabus file (PDF, DOCX, etc.)', null=True, upload_to='courses/syllabi/')),
                ('extracted_topics', models.JSONField(default=list, help_text='Topics extracted from syllabus content')),
                ('topics_summary', models.TextField(blank=True, help_text='AI-generated summary of course topics')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether the syllabus has been processed by the RAG pipeline')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if RAG processing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this topic belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='course_topics', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Topic',
                'verbose_name_plural': 'Course Topics',
                'db_table': 'courses_topic',
                'ordering': ['-created_at'],
            },
        ),
    ]
