# Generated by Django 5.2.6 on 2025-09-21 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseassignmentfile_coursequiz_coursetopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignmentfile',
            name='assignment',
            field=models.OneToOneField(blank=True, help_text='Assignment entry created from this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_file', to='courses.assignment'),
        ),
    ]
