# Generated by Django 5.2.6 on 2025-09-21 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseassignmentfile_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Topic title/name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the topic')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', help_text='Difficulty level of this topic', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this topic in the syllabus')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether this topic has been marked as completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this topic belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='topic_items', to='courses.course')),
                ('course_topic', models.ForeignKey(help_text='Parent CourseTopic (syllabus) this item was extracted from', on_delete=django.db.models.deletion.CASCADE, related_name='topic_items', to='courses.coursetopic')),
            ],
            options={
                'verbose_name': 'Course Topic Item',
                'verbose_name_plural': 'Course Topic Items',
                'db_table': 'courses_topic_item',
                'ordering': ['order', 'created_at'],
                'unique_together': {('course_topic', 'title')},
            },
        ),
    ]
