# Generated by Django 5.2.6 on 2025-09-28 16:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursetopicitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exam name or title', max_length=200)),
                ('exam_type', models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final Exam'), ('quiz', 'Quiz'), ('test', 'Test'), ('practical', 'Practical Exam'), ('oral', 'Oral Exam'), ('other', 'Other')], default='test', help_text='Type of exam', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Exam description or additional notes')),
                ('exam_date', models.DateTimeField(help_text='Date and time of the exam')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Exam duration in minutes', null=True)),
                ('location', models.CharField(blank=True, help_text='Exam location or room', max_length=200)),
                ('syllabus_coverage', models.JSONField(blank=True, default=list, help_text='List of topics/chapters covered in this exam with weightage')),
                ('total_weightage', models.DecimalField(decimal_places=2, default=100.0, help_text='Total weightage percentage in final grade', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', help_text='Current status of the exam', max_length=20)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, help_text='Grade received (percentage)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('preparation_status', models.JSONField(blank=True, default=dict, help_text='Study preparation progress for each topic')),
                ('study_plan_generated', models.BooleanField(default=False, help_text='Whether AI study plan has been generated for this exam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this exam belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'courses_exam',
                'ordering': ['exam_date'],
                'unique_together': {('course', 'name', 'exam_date')},
            },
        ),
    ]
