# Generated by Django 5.2.6 on 2025-09-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseassignmentfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='file',
        ),
        migrations.RemoveField(
            model_name='coursetopic',
            name='syllabus_file',
        ),
    ]
