# Generated by Django 5.2.6 on 2025-09-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_courseassignmentfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignmentfile',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename of uploaded file', max_length=255),
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename of uploaded file', max_length=255),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='syllabus_file',
            field=models.FileField(blank=True, help_text='Uploaded syllabus file (PDF, DOCX, etc.)', null=True, upload_to='courses/syllabi/'),
        ),
    ]
