# Generated by Django 5.2.6 on 2025-09-14 23:07

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Resource title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Resource description')),
                ('url', models.URLField(blank=True, help_text='Resource URL')),
                ('resource_type', models.CharField(blank=True, choices=[('article', 'Article'), ('video', 'Video'), ('book', 'Book'), ('course', 'Online Course'), ('tutorial', 'Tutorial'), ('documentation', 'Documentation'), ('paper', 'Research Paper'), ('quiz', 'Quiz/Practice'), ('tool', 'Tool/Software'), ('other', 'Other')], help_text='Type of resource', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Subject area (e.g., Mathematics, Computer Science)', max_length=100)),
                ('topics', models.JSONField(blank=True, default=list, help_text='List of topics covered by this resource')),
                ('difficulty_level', models.IntegerField(default=3, help_text='Difficulty level from 1 (beginner) to 5 (expert)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('estimated_time', models.DecimalField(blank=True, decimal_places=1, help_text='Estimated time to complete (in hours)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average user rating (0-5 stars)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this resource has been viewed')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this resource has been verified by an admin')),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Vector embedding for semantic search (pgvector-ready)', null=True, size=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by_user', models.ForeignKey(blank=True, help_text='User who added this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'db_table': 'resources_resource',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Collection name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Collection description')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this collection is publicly visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resources', models.ManyToManyField(blank=True, related_name='collections', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Collection',
                'verbose_name_plural': 'Resource Collections',
                'db_table': 'resources_resourcecollection',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='Optional review text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Rating',
                'verbose_name_plural': 'Resource Ratings',
                'db_table': 'resources_resourcerating',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type'], name='resources_r_resourc_1a6f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['subject'], name='resources_r_subject_c472a4_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['difficulty_level'], name='resources_r_difficu_ae3dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['rating'], name='resources_r_rating_f4fc68_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_verified'], name='resources_r_is_veri_12c07d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcecollection',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='resourcerating',
            unique_together={('resource', 'user')},
        ),
    ]
