# Generated by Django RAG implementation

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
import pgvector.django
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('courses', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        # Enable pgvector extension (run this manually in Heroku PostgreSQL)
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector CASCADE;"
        ),
        
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='The actual text content of this chunk')),
                ('chunk_type', models.CharField(
                    choices=[
                        ('text', 'Text Content'), 
                        ('syllabus', 'Syllabus Section'), 
                        ('assignment', 'Assignment Description'), 
                        ('quiz_info', 'Quiz Information'), 
                        ('lecture_notes', 'Lecture Notes'), 
                        ('textbook', 'Textbook Content'), 
                        ('research_paper', 'Research Paper'), 
                        ('video_transcript', 'Video Transcript')
                    ], 
                    default='text', 
                    help_text='Type of content this chunk represents', 
                    max_length=20
                )),
                ('embedding', pgvector.django.VectorField(dimensions=1536, help_text='Vector embedding for semantic search')),
                ('chunk_index', models.IntegerField(help_text='Position of this chunk in the original document')),
                ('word_count', models.IntegerField(help_text='Number of words in this chunk')),
                ('difficulty_level', models.IntegerField(
                    default=3, 
                    help_text='Difficulty level of this content (1=basic, 5=advanced)', 
                    validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]
                )),
                ('topics', models.JSONField(default=list, help_text='List of topics/concepts covered in this chunk')),
                ('learning_objectives', models.JSONField(default=list, help_text='Learning objectives this chunk addresses')),
                ('estimated_study_time', models.DecimalField(
                    blank=True, 
                    decimal_places=1, 
                    help_text='Estimated time to study this chunk (minutes)', 
                    max_digits=5, 
                    null=True
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(
                    help_text='Course this content is associated with', 
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='document_chunks', 
                    to='courses.course'
                )),
                ('resource', models.ForeignKey(
                    help_text='Parent resource this chunk belongs to', 
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='chunks', 
                    to='resources.resource'
                )),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'db_table': 'resources_document_chunk',
                'ordering': ['resource', 'chunk_index'],
            },
        ),
        
        migrations.CreateModel(
            name='StudyPlanContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_study_time_per_day', models.DecimalField(
                    decimal_places=1, 
                    default=2.0, 
                    help_text='Hours student prefers to study per day', 
                    max_digits=4
                )),
                ('preferred_difficulty_progression', models.CharField(
                    choices=[
                        ('gradual', 'Gradual increase'), 
                        ('mixed', 'Mixed difficulty'), 
                        ('front_loaded', 'Hardest topics first'), 
                        ('back_loaded', 'Easier topics first')
                    ], 
                    default='gradual', 
                    max_length=20
                )),
                ('learning_style', models.JSONField(
                    default=dict, 
                    help_text="Student's learning style preferences (visual, auditory, kinesthetic)"
                )),
                ('current_knowledge_level', models.JSONField(
                    default=dict, 
                    help_text="Student's self-assessed knowledge levels by topic"
                )),
                ('available_study_slots', models.JSONField(
                    default=list, 
                    help_text='Available time slots for studying (days/times)'
                )),
                ('assignments', models.JSONField(
                    default=list, 
                    help_text='List of assignments with due dates and requirements'
                )),
                ('quiz_schedule', models.JSONField(
                    default=list, 
                    help_text='Scheduled quizzes/exams with dates and topics'
                )),
                ('target_grade', models.CharField(
                    blank=True, 
                    help_text='Target grade (A+, A, B+, etc.)', 
                    max_length=5
                )),
                ('priority_topics', models.JSONField(
                    default=list, 
                    help_text='Topics student wants to prioritize'
                )),
                ('context_embedding', pgvector.django.VectorField(
                    blank=True, 
                    dimensions=1536, 
                    help_text='Vector embedding of the entire context for similarity matching', 
                    null=True
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='study_contexts', 
                    to='courses.course'
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='study_contexts', 
                    to='accounts.user'
                )),
            ],
            options={
                'verbose_name': 'Study Plan Context',
                'verbose_name_plural': 'Study Plan Contexts',
                'db_table': 'resources_study_plan_context',
                'unique_together': {('user', 'course')},
            },
        ),
        
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(help_text='Name of the topic/concept', max_length=200)),
                ('prerequisites', models.JSONField(default=list, help_text='List of prerequisite topics')),
                ('difficulty_level', models.IntegerField(
                    help_text='Difficulty level of this topic', 
                    validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]
                )),
                ('estimated_study_hours', models.DecimalField(
                    decimal_places=1, 
                    help_text='Estimated hours needed to master this topic', 
                    max_digits=5
                )),
                ('topic_embedding', pgvector.django.VectorField(
                    dimensions=1536, 
                    help_text='Vector representation of this topic'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='knowledge_graphs', 
                    to='courses.course'
                )),
            ],
            options={
                'verbose_name': 'Knowledge Graph Node',
                'verbose_name_plural': 'Knowledge Graph Nodes',
                'db_table': 'resources_knowledge_graph',
                'unique_together': {('course', 'topic_name')},
            },
        ),
        
        migrations.CreateModel(
            name='RAGQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='The original query from the user')),
                ('query_type', models.CharField(
                    choices=[
                        ('study_plan_creation', 'Study Plan Creation'), 
                        ('study_plan_modification', 'Study Plan Modification'), 
                        ('resource_recommendation', 'Resource Recommendation'), 
                        ('concept_explanation', 'Concept Explanation'), 
                        ('schedule_optimization', 'Schedule Optimization')
                    ], 
                    help_text='Type of RAG query', 
                    max_length=50
                )),
                ('query_embedding', pgvector.django.VectorField(
                    dimensions=1536, 
                    help_text='Vector embedding of the query'
                )),
                ('retrieved_chunks', models.JSONField(help_text='IDs and scores of retrieved document chunks')),
                ('generated_response', models.TextField(help_text='AI-generated response')),
                ('response_quality_score', models.DecimalField(
                    blank=True, 
                    decimal_places=2, 
                    help_text='Quality score of the generated response (0-1)', 
                    max_digits=3, 
                    null=True
                )),
                ('user_feedback', models.CharField(
                    blank=True, 
                    choices=[
                        ('helpful', 'Helpful'), 
                        ('partially_helpful', 'Partially Helpful'), 
                        ('not_helpful', 'Not Helpful')
                    ], 
                    max_length=20, 
                    null=True
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='rag_queries', 
                    to='accounts.user'
                )),
            ],
            options={
                'verbose_name': 'RAG Query',
                'verbose_name_plural': 'RAG Queries',
                'db_table': 'resources_rag_query',
                'ordering': ['-created_at'],
            },
        ),
        
        # Add ManyToMany relationship for KnowledgeGraph
        migrations.AddField(
            model_name='knowledgegraph',
            name='related_chunks',
            field=models.ManyToManyField(
                blank=True, 
                help_text='Document chunks that cover this topic', 
                to='resources.documentchunk'
            ),
        ),
        
        # Note: Concurrent indexes will be created in a separate migration
        
        # Add regular indexes for filtering
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['chunk_type'], name='resources_documentchunk_chunk_type_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['difficulty_level'], name='resources_documentchunk_difficulty_level_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['course'], name='resources_documentchunk_course_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgegraph',
            index=models.Index(fields=['difficulty_level'], name='resources_knowledgegraph_difficulty_level_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgegraph',
            index=models.Index(fields=['course'], name='resources_knowledgegraph_course_idx'),
        ),
    ]




