# Generated by Django - pgvector concurrent indexes

from django.db import migrations


class Migration(migrations.Migration):
    """
    Non-atomic migration for creating pgvector indexes.
    PostgreSQL requires CREATE INDEX CONCURRENTLY to run outside transactions.
    """

    atomic = False  # This is crucial - disables transaction wrapping

    dependencies = [
        ('resources', '0002_rag_models'),
    ]

    operations = [
        # Create pgvector indexes for optimal similarity search performance
        migrations.RunSQL(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS document_chunk_embedding_cosine_idx 
            ON resources_document_chunk 
            USING ivfflat (embedding vector_cosine_ops) 
            WITH (lists = 1000);
            """,
            reverse_sql="DROP INDEX IF EXISTS document_chunk_embedding_cosine_idx;"
        ),
        
        migrations.RunSQL(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS study_plan_context_embedding_cosine_idx 
            ON resources_study_plan_context 
            USING ivfflat (context_embedding vector_cosine_ops) 
            WITH (lists = 100);
            """,
            reverse_sql="DROP INDEX IF EXISTS study_plan_context_embedding_cosine_idx;"
        ),
        
        migrations.RunSQL(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS knowledge_graph_embedding_cosine_idx 
            ON resources_knowledge_graph 
            USING ivfflat (topic_embedding vector_cosine_ops) 
            WITH (lists = 100);
            """,
            reverse_sql="DROP INDEX IF EXISTS knowledge_graph_embedding_cosine_idx;"
        ),
    ]


