# Generated by Django 5.2.6 on 2025-09-21 21:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_add_course_and_file_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Document title', max_length=500)),
                ('content', models.TextField(help_text='Full document content or excerpt')),
                ('document_type', models.CharField(choices=[('course_quiz', 'Course Quiz'), ('course_assignment', 'Course Assignment'), ('course_syllabus', 'Course Syllabus'), ('resource', 'Resource Document'), ('textbook', 'Textbook'), ('research_paper', 'Research Paper'), ('lecture_notes', 'Lecture Notes'), ('other', 'Other')], default='other', help_text='Type of document', max_length=50)),
                ('source_url', models.URLField(blank=True, help_text='Source URL or file path')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resources_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(db_index=True, help_text='Main topic or concept', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the topic')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence in topic extraction (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resources_knowledge_node',
                'ordering': ['-confidence_score', 'topic'],
            },
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='resources_d_chunk_t_c4218f_idx',
            old_name='resources_documentchunk_chunk_type_idx',
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='resources_d_difficu_15ef7b_idx',
            old_name='resources_documentchunk_difficulty_level_idx',
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='resources_d_course__e7c366_idx',
            old_name='resources_documentchunk_course_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgegraph',
            new_name='resources_k_difficu_cfd4a1_idx',
            old_name='resources_knowledgegraph_difficulty_level_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgegraph',
            new_name='resources_k_course__cc2b5f_idx',
            old_name='resources_knowledgegraph_course_idx',
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='resource',
            field=models.ForeignKey(blank=True, help_text='Parent resource this chunk belongs to (if from resource)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='resources.resource'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='resources_d_documen_a09e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='resources_d_created_512555_idx'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Parent document this chunk belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='resources.document'),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='related_chunks',
            field=models.ManyToManyField(blank=True, help_text='Document chunks related to this knowledge node', related_name='knowledge_nodes', to='resources.documentchunk'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['topic'], name='resources_k_topic_c74423_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['confidence_score'], name='resources_k_confide_033409_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['created_at'], name='resources_k_created_7d9193_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgenode',
            constraint=models.UniqueConstraint(fields=('topic',), name='unique_knowledge_node_topic'),
        ),
    ]
