# Generated by Django 5.2.6 on 2025-09-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_document_knowledgenode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
    ]
