# Generated by Django 5.2.6 on 2025-09-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_remove_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename of uploaded file', max_length=255),
        ),
    ]
